#!/bin/bash
#clear

# Executable directory
BIN=/n/ras/people/mircea/map/bin
#BIN=/export/fox/processed/bin

#Field
FIELD="S1"

#Band
BAND="0"

#Central frequency
CNTRFRQ="1450"

#RA min & max
RAMIN="59.1"
RAMAX="145"

#DEC min & max
DECMIN="-1.05"
DECMAX="17.05"

#CELLSIZE max resolution is 3.5
CELLSIZE="1.0"

#radius of spread, multiple of resolution 3.5, recommended 1.5 - 2.0
PATCH="2.0"

# 1 upscan, 2 downscan, 3 both, for creating images
GRIDTYPE="3"

BALGAIN="0.142"

BALEPSILON="0.000001"

BWORDER="8"

DECORDER="16"

SOURCE="GALFACTS_S1"

# First channel
LOWCHAN="0"

# Last channel
HIGHCHAN="1"

# AVG=1 for average image, AVG=0 for cube
AVG="1"

# AVG first channel
AVG_LOWCHAN="264"

# AVG last channel
AVG_HIGHCHAN="4000"

$BIN/map4096 multibeam $CNTRFRQ $LOWCHAN $HIGHCHAN $RAMIN $RAMAX $DECMIN $DECMAX $CELLSIZE $PATCH $GRIDTYPE $BALGAIN $BALEPSILON $BWORDER $DECORDER $AVG $AVG_LOWCHAN $AVG_HIGHCHAN "$SOURCE" $FIELD $BAND
