#!/bin/bash
#clear

# Executable directory
BIN=/n/ras/people/mircea/map/bin

#Field
FIELD="S1"

#Band
BAND="0"

#Central frequency
CNTRFRQ="1450"

#RA min & max
RAMIN="59.1"
RAMAX="145"

#DEC min & max
DECMIN="-1.05"
DECMAX="17.05"

#CELLSIZE max resolution is 3.5
CELLSIZE="1.0"
#CELLSIZE="0.5"

#radius of spread, multiple of resolution 3.5, recommended 1.5 - 2.0
PATCH="2.0"

# 1 upscan, 2 downscan, 3 both, for creating images
GRIDTYPE="3"

DAYFIT="100"

SCANFIT="100"

BALGAIN="0.142"

BALEPSILON="0.000001"

BWORDER="8"

DECORDER="16"

SOURCE="GALFACTS_S1"

# AVG=0 for average image, AVG=1,2,... for cube
AVG="10"

# AVG first channel
AVG_LOWCHAN="264"

# AVG last channel
AVG_HIGHCHAN="4000"

# First channel
LOWCHAN="1224"
# Last channel
HIGHCHAN="1344"
$BIN/map4096 multibeam $CNTRFRQ $LOWCHAN $HIGHCHAN $RAMIN $RAMAX $DECMIN $DECMAX $CELLSIZE $PATCH $GRIDTYPE $BALGAIN $BALEPSILON $BWORDER $DECORDER $AVG $AVG_LOWCHAN $AVG_HIGHCHAN "$SOURCE" $FIELD $BAND &

# First channel
LOWCHAN="1344"
# Last channel
HIGHCHAN="1464"
$BIN/map4096 multibeam $CNTRFRQ $LOWCHAN $HIGHCHAN $RAMIN $RAMAX $DECMIN $DECMAX $CELLSIZE $PATCH $GRIDTYPE $BALGAIN $BALEPSILON $BWORDER $DECORDER $AVG $AVG_LOWCHAN $AVG_HIGHCHAN "$SOURCE" $FIELD $BAND &

# First channel
LOWCHAN="1464"
# Last channel
HIGHCHAN="1584"
$BIN/map4096 multibeam $CNTRFRQ $LOWCHAN $HIGHCHAN $RAMIN $RAMAX $DECMIN $DECMAX $CELLSIZE $PATCH $GRIDTYPE $BALGAIN $BALEPSILON $BWORDER $DECORDER $AVG $AVG_LOWCHAN $AVG_HIGHCHAN "$SOURCE" $FIELD $BAND &

# First channel
LOWCHAN="1584"
# Last channel
HIGHCHAN="1704"
$BIN/map4096 multibeam $CNTRFRQ $LOWCHAN $HIGHCHAN $RAMIN $RAMAX $DECMIN $DECMAX $CELLSIZE $PATCH $GRIDTYPE $BALGAIN $BALEPSILON $BWORDER $DECORDER $AVG $AVG_LOWCHAN $AVG_HIGHCHAN "$SOURCE" $FIELD $BAND &

